replicaCount: 1
image:
  repository: 836759839628.dkr.ecr.ap-south-1.amazonaws.com/prod/api
  tag: "null-1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  PGDATABASE: "postgres"
  PGUSER: "postgres"
  PGPASSWORD: "postgres"