replicaCount: 1

image:
  repository: 836759839628.dkr.ecr.ap-south-1.amazonaws.com/prod/web
  tag: "null-1"
  pullPolicy: IfNotPresent

service:
  name: web-service
  type: LoadBalancer
  port: 80
  targetPort: 8080

deployment:
  containerPort: 8080
